### ISSUE TITLE
How to disable guidelines directly in code and/or at object level

### ISSUE THREAD

**Issue by ffm145** [Trivadis/plsql-cop-validators#26]
Sometimes a few guidelines throw false positive errors. I don't want to disable these guidelines in general because they are correct most of the time.

So my question is if it is possible to disable a guideline directly in PL/SQL code? If not, is it possible to implement this feature in one of the next versions?

Here is an example for G-1050 (Avoid using literals in your code) and G-2110 (Try to use anchored declarations for variables, constants and types) with use of some annotation:
```sql
create or replace procedure demo authid definer is
  c_text constant varchar2(50 char):='Result: ';
  --%PLSQLCOP_DISABLE:2110
  l_result varchar2(50 char);  
begin
  --%PLSQLCOP_DISABLE:1050
  select max('a'||level)
    into l_result
    from dual
 connect by level<4;

 sys.dbms_output.put_line(c_text||l_result);
end;
/
```

Maybe it is easier to create a new argument in plsql-cop-cli and pass a list of objects with the additional guidelines to disable!?

Something like 
```
bash
    skipextra=<name>:<list>[|]    pipe separated list of objectname and comma separated guidelines pairs to skip

tvdcc path=C:\temp skipextra=demo.prc:2110,1050|udaf_function.fnc:7410
```

What do you think about???

**Comment by PhilippSalvisberg** [comment]
We support the `NOSONAR` marker comment for that purposes, as other SonarQube analyzers (see https://docs.sonarqube.org/7.9/faq/).

I've added it to your example:

```sql 
create or replace procedure demo authid definer is
  c_text constant varchar2(50 char):='Result: ';
  l_result varchar2(50 char);  -- NOSONAR:2110
begin
  select max('a'||level)  -- NOSONAR:1050
    into l_result
    from dual
 connect by level<4;

 sys.dbms_output.put_line(c_text||l_result);
end;
/
```

Please note that the guideline number `2110` in `-- NOSONAR:2110` is treated as an additional comment. It has no effect. The `NOSONAR` comment suppresses all guideline violations on this line, except `G-0000: Avoid using the NOSONAR marker.`. The pseudo guideline `G-0000` can be disabled as any other guideline in general. 

There is also a `nosonar` option for the CLI (see https://github.com/Trivadis/plsql-cop-cli#usage) and an option `Honor NOSONAR marker comments` for the SQL Developer extension to enable/disable the support of `NOSONAR` marker comments. It's enabled by default.

Does that help?




G-0000: Avoid using the NOSONAR marker.
--

**Comment by ffm145** [comment]
Yes. That helps a lot and is exactly what I need.

Thank you very much!

**Comment by PhilippSalvisberg** [comment]
Thank you for your fast feedback. I'm closing the issue now.
