### ISSUE TITLE
Question: how do you generate the "rules.xml" file for a new validator?

### ISSUE THREAD

**Issue by deboiph** [Trivadis/plsql-cop-validators#39]
Hello,

I have created a new db* CODECOP validator (named DBCCGuidelines3Plus) as a modified copy of TrivadisGuidelines3Plus.

I can't find a way to generate the "src/main/resources/DBCCGuidelines3Plus" folder and its subfolders, including the "rules.xml" file.

The following comment in "rules.xml" makes me say that this XML file should be generated in some way: generated by db* CODECOP using the genmodel option

I do see a few references to "genmodel" in the "pom.xml" file and I have duplicated some lines as necessary but it doesn't help.

Any hint?

While waiting for your reply, I have created the "DBCCGuidelines3Plus" folder as a copy of "src/main/resources/TrivadisGuidelines3Plus" but the messages contained in the "rules.xml" file are of course the Trivadis ones and not mine. Apart from that, my custom validator works perfectly with both SQL Developer and SonarQube.

Thanks for the great job!

**Comment by PhilippSalvisberg** [comment]
The genmodel for TrivadisGuidelines3Plus is generated in the POM: https://github.com/Trivadis/plsql-cop-validators/blob/v4.0.0/pom.xml#L174-L180 . 

This is the generator used: https://github.com/Trivadis/plsql-cop-validators/blob/v4.0.0/src/main/java/com/trivadis/tvdcc/generators/TrivadisGuidelines3PlusGenmodel.java 

The result is used in https://github.com/Trivadis/plsql-cop-validators/blob/v4.0.0/src/main/java/com/trivadis/sonar/plugin/TrivadisGuidelines3PlusValidatorConfig.java .
