### ISSUE TITLE
"WARNING: An illegal reflective access operation has occurred" building custom validator

### ISSUE THREAD

**Issue by mhoys** [Trivadis/plsql-cop-validators#40]
Hi,
I'm trying to build a custom validator from the 4.1.1. source code, and I'm getting the following warning:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/C:/Users/mhoys/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Any idea if this error is critical, or can it be ignored? I tried with a higher version of Java, but I'm getting the same warning.

Following tools were used:
- Maven 3.6.3
- TVDCC 4.1.3
- Windows 10
- jdk-11.0.2
 
Thanks,
Matthias

**Comment by PhilippSalvisberg** [comment]
You get this error during build time only. You can ignore it. It's caused by Xtext / Xtend 2.25.0 which still use Google Guice 3.0. 

At runtime artifacts we use Google Guice 5.0.1 which does not throw this warning anymore. I expect that future versions of Xtext / Xtend will update the version for Guice.

**Comment by mhoys** [comment]
Ok, thanks Philipp!
