### ISSUE TITLE
Migrate from Xtend to Java

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/plsql-cop-validators#42]
To make the validators work in any db* CODECOP supported environment Java 8 compatibility is necessary for the runtime classes. For test classes Java 17 can be used, which is helpful to replace the multiline strings for SQL and PL/SQL code in the test classes.

Using Java instead of Xtend should make it easier to get started in any IDE.

**Comment by mhoys** [comment]
Hi Philipp, we were using a custom-made Xtend file with our own validations with db*CODECOP version 4.3, but this no longer seems to work with version 5.0.1. I think I will have to convert our custom Xtend files to Java. Is there an easy way to convert Xtend files to Java?

**Comment by PhilippSalvisberg** [comment]
>Is there an easy way to convert Xtend files to Java?

Yes, you could use the file generated by Xtend, but it doesn't look lovely.

I've written a [this blog post](https://www.salvis.com/blog/2020/06/06/bye-bye-xtend-welcome-java/) some time ago with a step-by-step guide. This should help.

**Comment by mhoys** [comment]
Thanks Philipp! Looks to be working fine indeed.
