### ISSUE TITLE
G-3120 triggering for local variables?

### ISSUE THREAD

**Issue by SiShaman** [Trivadis/plsql-cop-validators#54]
"I noticed it also tells me to prefix local variables used in the selected columns."

_Originally posted by @DominiqueComte in https://github.com/Trivadis/plsql-cop-validators/issues/4#issuecomment-525639965_

Was this issue ever addressed? I'm seeing it specifically in an INSERT ... SELECT ... block.

**Comment by PhilippSalvisberg** [comment]
Can you please post an example? Thank you.

**Comment by SiShaman** [comment]
I'll get one to you tomorrow. It will take some time to "anonymize" the code such that I can share it. Very broadly it's something like this, though:

```
INSERT INTO Table1 (C1, C2, C3)
SELECT T2.ColName, localVar, anotherLocal
FROM Table2 T2
INNER JOIN Table3 T3 ON T2.ColName = T3.OtherCol
WHERE T2.ColName < 20;
```
And I get two reports of G-3120 on the SELECT line, apparently for localVar and anotherLocal.

**Comment by PhilippSalvisberg** [comment]
Thanks. I can reproduce it:

```sql
declare
   l_var1 integer := 1;
   l_var2 integer := 2;
begin
   insert into tab1 (c1, c2, c3)
   select t2.c4, l_var1, l_var2
     from tab2 t2
    inner join tab3 t3
       on t2.c5 = t3.c5
    where t2.c4 < 20;
end;
/
```

<img width="930" alt="image" src="https://user-images.githubusercontent.com/3883171/192449289-51a19059-c412-4818-952a-5640e3ef084d.png">

These are false positives. I consider this a validator bug.

**Comment by PhilippSalvisberg** [comment]
fixed via PLSQLCOP-441: G-3120: False positive when using local variables in the select list.

will be part of the next version of db* CODECOP.

**Comment by SiShaman** [comment]
Thanks for the quick resolution. Looking forward to the update.
