### ISSUE TITLE
How to setup the development environment?

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-cop-validators#6]
My steps currently:
I forked this github project and imported it into Eclipse DSL.
But there are severall imports missing when opening e.g. the TrivadisGuidelines3Plus.xtend .

On the PLSQL Cop Homepage [(Link)](https://www.salvis.com/blog/plsql-cop/) it is mentioned that there is a sample maven project but after downloading PLSQL Cop from there I dont see that.

Is there a simple instruction, what to download and how to setup so I can extend/modify the validator?

**Comment by PhilippSalvisberg** [comment]
Follow the instructions [here](https://github.com/Trivadis/cop-validators#how-to-build). The [Maven build file](https://github.com/Trivadis/cop-validators/blob/master/pom.xml) is now part of this repo.

**Comment by PhilippSalvisberg** [comment]
As first step ensure you can build it via command line.

When it works then set up the IDE. I recommend to download the [Eclipse IDE for Java and DSL Developers](https://www.eclipse.org/downloads/packages/release/2019-09/r/eclipse-ide-java-and-dsl-developers). Then Xtend should be working fine. You may import an existing Maven project. You'll get errors when tvdcc is not installed in the expected directory. No problem. just amend the configuration for `tvdcc.basedir` in the `pom.xml`.

**Comment by PhilippSalvisberg** [comment]
Closing. Considered answered.
