### ISSUE TITLE
Does db*CODECOP support regular expression strings when modifying its settings to change the default values?

### ISSUE THREAD

**Issue by DavidotNet** [Trivadis/plsql-cop-validators#64]
I want to provide a regular expression value as show to replace the default   l_   value such that the validation rule will permit a range of acceptable values according to my preferences.

  PREFIX_LOCAL_VARIABLE_NAME = "^(c_|v_|h_|k_|i_|n_|aa_|nt_|va_|cur_|rec_).*";

**Comment by PhilippSalvisberg** [comment]
No.

Aas you can see in https://github.com/Trivadis/plsql-cop-validators/blob/9839cb6535fb7f9133f212bfaa9877c3454228be/src/main/java/com/trivadis/tvdcc/validators/TrivadisPlsqlNaming.java#L311 the validator uses `startsWith` to check the prefix. As a result, configuring a regular expression won't work.

The validators [TrivadisPlsqlNaming](https://github.com/Trivadis/plsql-cop-validators/tree/main?tab=readme-ov-file#trivadisplsqlnaming) and [GLP](https://github.com/Trivadis/plsql-cop-validators/tree/main?tab=readme-ov-file#glp) can be used as an example/template/base to implement the checks to match your naming convention requirements.
