### ISSUE TITLE
How to inspect Declaration of Datatypes from JAR File.

### ISSUE THREAD

**Issue by L-K-Primus** [Trivadis/plsql-cop-validators#7]
I've managed setting up a developement workspace in eclipse by following the steps provided [here](https://github.com/Trivadis/cop-validators/issues/6).
Now I cant open the declaration of types like VariableDeclaration. All I get then is "Source not found". How can I access the declaration of these types? 

Edit:
Ultimately i want to overwrite an existing validator to meet my requirements and in order to achieve that I need to understand what data is provided to the validator.

**Comment by PhilippSalvisberg** [comment]
Can you build the the cop-validtors project sucessfully?

**Comment by L-K-Primus** [comment]
Sorry for the late answer.
Yes, im able to build it.

To give you a detailed example: In TrivadisGuidelines3Plus.xtend in Eclipse DSL, when rightclicking on PLSQLCopGuideline, then on Open Declaration, I get "Source not Found".
Is this normal behavior or have i configured something incorrectly?

**Comment by PhilippSalvisberg** [comment]
Yes, this is expected behavior. The Source of `PLSQLCopGuideline` is not available, only the class file.

**Comment by L-K-Primus** [comment]
Thanks for the quick answer.
